apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: jenkins
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      imagePullSecrets:
        - name: regcred

      containers:
      - name: nodejs
        image: ghcr.io/cuongtv97/nodejs:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
